version: '3'
services:
  grpc-memoapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:8080
    image: grpc-memoapp:latest
    volumes:
      - ./:/app
      - go_module_data:/go
volumes:
  go_module_data:
